### ISSUE TITLE
Npm run dev wrong.

### ISSUE THREAD

**Issue by LixvYang** [mlogclub/bbs-go#170]
When I run 
```
npm run dev
```
bugs.....
```
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/lixin/code/github.com/bbs-go/site/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/lixin/code/github.com/bbs-go/site/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/lixin/code/github.com/bbs-go/site/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/lixin/code/github.com/bbs-go/site/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/lixin/code/github.com/bbs-go/site/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/lixin/code/github.com/bbs-go/site/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/lixin/code/github.com/bbs-go/site/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/lixin/code/github.com/bbs-go/site/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/lixin/code/github.com/bbs-go/site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/lixin/code/github.com/bbs-go/site/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/lixin/code/github.com/bbs-go/site/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by LixvYang** [comment]
So fix it to add 
```
export NODE_OPTIONS=--openssl-legacy-provider
```
then
```
npm run dev
```

bugs fixed.
